name: ReportPlayer
version: 1.5.2
main: me.Coderforlife.Report.Main

commands:
    report:
        description: Reports the player
        usage: /<command> [player]
        
        
permissons:
    report.command:
        default: true
    report.view:
        default: op